### ISSUE TITLE
 [Reanimated] `UpdatePropsManager` is not available on non-native platform.      at Handler 

### ISSUE THREAD

**Issue by TallNutAlt** [GFean/rn-gesture-swipeable-flatlist#13]
Error reported after use
 [Reanimated] `UpdatePropsManager` is not available on non-native platform.      at Handler

**Comment by TallNutAlt** [comment]
`<SwipeableFlatList
          // onEndReachedThreshold={0.5}
          // onEndReached={() => onEndRefresh()}
          data={pageList}
          keyExtractor={item => item.id}
          renderItem={({item, index}) => (
            <PageViewRender item={item} index={index} />
          )}
          renderRightActions={renderRightActions}
        />`

**Comment by GFean** [comment]
@TallNutAlt , Hi. Are you sure this is related to this library ? This package doesn't even use reanimated.
I've found the error you've mentioned [here, in react-native-reanimateds repo](https://github.com/software-mansion/react-native-reanimated/issues/5468).

Also, which platform are you on ?

**Comment by TallNutAlt** [comment]
> @TallNutAlt , Hi. Are you sure this is related to this library ? This package doesn't even use reanimated. I've found the error you've mentioned [here, in react-native-reanimateds repo](https://github.com/software-mansion/react-native-reanimated/issues/5468).
> 
> Also, which platform are you on ?

Thank you for your reply. It may be related to the library, but this issue does not occur every time I comment out renderItem

**Comment by TallNutAlt** [comment]
@GFean This is related to react-native-gesture-handler have sth. to do with

**Comment by GFean** [comment]
> > @TallNutAlt , Hi. Are you sure this is related to this library ? This package doesn't even use reanimated. I've found the error you've mentioned [here, in react-native-reanimateds repo](https://github.com/software-mansion/react-native-reanimated/issues/5468).
> > Also, which platform are you on ?
> 
> Thank you for your reply. It may be related to the library, but this issue does not occur every time I comment out renderItem

I'd suggest to debug this further, this might be related to the component you have in your renderItem. Can't say anything for sure, because I don't know what's inside that `PageViewRender ` component 🤷‍♂️ 
Try replacing it with another component and see if it works. 
I'm happy to assist you further if this occurs to be the problem with the library.

**Comment by GFean** [comment]
> @GFean This is related to react-native-gesture-handler have sth. to do with

which version of the gesture handler are you using ? also, is your project managed by expo or you use RN CLI ?

**Comment by TallNutAlt** [comment]
@GFean I tried an empty component, but it still has issues

**Comment by TallNutAlt** [comment]
> > @GFean This is related to react-native-gesture-handler have sth. to do with
> 
> which version of the gesture handler are you using ? also, is your project managed by expo or you use RN CLI ?

    "react-native-gesture-handler": "^2.16.2",
      "rn-gesture-swipeable-flatlist": "^2.3.0"
      rn cli

**Comment by TallNutAlt** [comment]
> > @GFean This is related to react-native-gesture-handler have sth. to do with
> 
> which version of the gesture handler are you using ? also, is your project managed by expo or you use RN CLI ?

This library uses "react-native-reanimated": "^2.3.1"

**Comment by GFean** [comment]
> > > @GFean This is related to react-native-gesture-handler have sth. to do with
> > 
> > 
> > which version of the gesture handler are you using ? also, is your project managed by expo or you use RN CLI ?
> 
> This library uses "react-native-reanimated": "^2.3.1"

So you're using latest version of the `react-native-gesture-handler` and older version of `react-native-reanimated`, they might have compatibility issues. It's really hard to say something for sure because of the lack of information. If you can give me a minimum reproducible example, I could try to resolve your issue.
Also, it might be worth for you to check out my [example app](https://github.com/GFean/rn-gesture-swipeable-flatlist-example) using this library.

**Comment by TallNutAlt** [comment]
> > > > @GFean This is related to react-native-gesture-handler have sth. to do with
> > > 
> > > 
> > > which version of the gesture handler are you using ? also, is your project managed by expo or you use RN CLI ?
> > 
> > 
> > This library uses "react-native-reanimated": "^2.3.1"
> 
> So you're using latest version of the `react-native-gesture-handler` and older version of `react-native-reanimated`, they might have compatibility issues. It's really hard to say something for sure because of the lack of information. If you can give me a minimum reproducible example, I could try to resolve your issue. Also, it might be worth for you to check out my [example app](https://github.com/GFean/rn-gesture-swipeable-flatlist-example) using this library.

just a moment

**Comment by TallNutAlt** [comment]
@GFean 
I encountered some issues while creating examples
I'm sorry, but it seems like I can't start it using the relevant environment
My project used "react-native-reanimated": "^3.5.4"
react-native-gesture-handler  Then it was used "react-native-reanimated": "^2.3.1"
And after that, it couldn't run anymore

**Comment by anasvemmully** [comment]
any update on this issue,, because iam struggling, I started a discussion https://github.com/software-mansion/react-native-reanimated/discussions/6359, I explained my issue there. Iam on my way to create an example.

but now I am receiving this error
 _**UpdatePropsManager is not available on non-native platform. at Handler**_

**Comment by TallNutAlt** [comment]
> any update on this issue,, because iam struggling, I started a discussion [software-mansion/react-native-reanimated#6359](https://github.com/software-mansion/react-native-reanimated/discussions/6359), I explained my issue there. Iam on my way to create an example.
> 
> but now I am receiving this error _**UpdatePropsManager is not available on non-native platform. at Handler**_
At present, there is no

**Comment by TallNutAlt** [comment]
> 有关于这个问题的更新吗？因为我正在苦苦挣扎，所以我开始了讨论[software-mansion/react-native-reanimated#6359](https://github.com/software-mansion/react-native-reanimated/discussions/6359)，我在那里解释了我的问题。我正在创建一个示例。
> 
> 但现在我收到此错误 _**UpdatePropsManager 在非本机平台上不可用。在 Handler**_

At present, there is no

**Comment by TallNutAlt** [comment]
> any update on this issue,, because iam struggling, I started a discussion [software-mansion/react-native-reanimated#6359](https://github.com/software-mansion/react-native-reanimated/discussions/6359), I explained my issue there. Iam on my way to create an example.
> 
> but now I am receiving this error _**UpdatePropsManager is not available on non-native platform. at Handler**_

At present, there is no

**Comment by anasvemmully** [comment]
```
diff --git a/node_modules/react-native-reanimated/src/UpdateProps.ts b/node_modules/react-native-reanimated/src/UpdateProps.ts
index 2f0941c..0033613 100644
--- a/node_modules/react-native-reanimated/src/UpdateProps.ts
+++ b/node_modules/react-native-reanimated/src/UpdateProps.ts
@@ -116,9 +116,13 @@ if (shouldBeUseWeb()) {
     // Jest attempts to access a property of this object to check if it is a Jest mock
     // so we can't throw an error in the getter.
     if (!isJest()) {
-      throw new Error(
-        '[Reanimated] `UpdatePropsManager` is not available on non-native platform.'
-      );
+      runOnUIImmediately(() => {
+        'worklet';
+        global.UpdatePropsManager = createUpdatePropsManager();
+      })();
+      // throw new Error(
+      //   '[Reanimated] `UpdatePropsManager` is not available on non-native platform.'
+      // );
     }
   };
   global.UpdatePropsManager = new Proxy({} as UpdatePropsManager, {
diff --git a/node_modules/react-native-reanimated/src/layoutReanimation/sharedTransitions/ProgressTransitionManager.ts b/node_modules/react-native-reanimated/src/layoutReanimation/sharedTransitions/ProgressTransitionManager.ts
index 68ea294..fead066 100644
--- a/node_modules/react-native-reanimated/src/layoutReanimation/sharedTransitions/ProgressTransitionManager.ts
+++ b/node_modules/react-native-reanimated/src/layoutReanimation/sharedTransitions/ProgressTransitionManager.ts
@@ -229,9 +229,13 @@ if (shouldBeUseWeb()) {
     // Jest attempts to access a property of this object to check if it is a Jest mock
     // so we can't throw an error in the getter.
     if (!isJest()) {
-      throw new Error(
-        '[Reanimated] `ProgressTransitionRegister` is not available on non-native platform.'
-      );
+      runOnUIImmediately(() => {
+        'worklet';
+        global.ProgressTransitionRegister = createProgressTransitionRegister();
+      })();
+      // throw new Error(
+      //   '[Reanimated] `ProgressTransitionRegister` is not available on non-native platform.'
+      // );
     }
   };
   global.ProgressTransitionRegister = new Proxy(
```

I soved the issue with this patch

but now I am getting this error

![image](https://github.com/user-attachments/assets/07c92b39-9d12-4ead-a15a-dce1cd7740ca)

this is happening inside `_updatePropsJS` function @ 53
node_modules/react-native-reanimated/src/js-reanimated/index.ts

**Comment by GFean** [comment]
Hi both, as mentioned above, I don't think the issues you're having are related to my package, because it only includes external libraries as peerDependencies, I suggest opening this issue in react-native-reanimated repo.
@anasvemmully  @TallNutAlt
