### ISSUE TITLE
possible to close the rest of row if one already openned?

### ISSUE THREAD

**Issue by zero-excelpoint** [GFean/rn-gesture-swipeable-flatlist#4]

**Comment by GFean** [comment]
Hello, this is not yet possible, I'm going to implement this ASAP. Sounds like a good idea

**Comment by GFean** [comment]
@zero-excelpoint  there you go: https://github.com/GFean/rn-gesture-swipeable-flatlist/releases/tag/v1.1.13

I've just implemented that functionality, npm package has also been updated. Just keep in mind, that you'll from now on will have to install react-native-gesture-handler manually, to make sure that you get your project compatible version
