### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by brrradley** [GFean/rn-gesture-swipeable-flatlist#5]
This error appears when i run my app.

```TypeError: null is not an object (evaluating 'dispatcher.useCallback')```

**Comment by brrradley** [comment]
Nevermind, i see you don't answer issues.

**Comment by GFean** [comment]
Hello, sorry for the late response,  did you go through the necessary installation steps ? also, can you give more description of your issue, like the version of react-native and so on. Also, here's an example project which might help: https://github.com/GFean/rn-gesture-swipeable-flatlist-example

**Comment by brrradley** [comment]
Thanks. I've since found other packages that suit my project.

**Comment by GFean** [comment]
@decafdevio  Well, I'm sorry for that. It's hard to dedicate time to this, since I have a lot of the other work. I'll close this issue with this comment then. If someone will face the same error, feel free to reopen this or open the new issue.
