### ISSUE TITLE
how to close opened action when click on any action

### ISSUE THREAD

**Issue by HarwinderSingh15** [GFean/rn-gesture-swipeable-flatlist#7]
Hi, 

Is there any way that i can close the opened action when i press action button,

Thanks

**Comment by GFean** [comment]
I'll add This functionality soon. Thanks !

**Comment by GFean** [comment]
Hi @HarwinderSingh15 , in the latest version, which is v2.3.0 at the moment a new method has been added `closeAnyOpenRows `. Which is accessible via ref alongside with other flatlist methods and can be used to close any opened action from anywhere you wish. 
Readme has also been updated and the example app as well. 
I'll close this issue right now, feel free to reopen it if something doesn't work.
Thanks !
