### ISSUE TITLE
Unable to start after installation

### ISSUE THREAD

**Issue by TallNutAlt** [GFean/rn-gesture-swipeable-flatlist#8]
error: node_modules\react-native\node_modules\deprecated-react-native-prop-types\index.js: The "id" argument must be of type string. Received undefined

**Comment by GFean** [comment]
Hi, if this is still relevant please update to version 2.0.1 which is latest for now and try again. 
If the update won't help, please provide a minimum reproducible example 🙏

**Comment by GFean** [comment]
I'm closing this issue, because I haven't heard from you for a while.
Feel free to reopen this, if this is still active.
